[package]
name = "doc-generator"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html = "0.6.3"
spec-decomposition.workspace = true